apiVersion: networking.istio.io/v1
kind: VirtualService

metadata:
  name: app-service-mesh-routes

spec:
  hosts:
  - app-service-mesh-svc.app.svc.cluster.local
  http:
    - route:
      - destination:
          host: app-service-mesh-svc.app.svc.cluster.local
          subset: V1
        weight: 80
      - destination:
          host: app-service-mesh-svc.app.svc.cluster.local
          subset: V2
        weight: 20